package com.myspace.risk_analytics_orchestrator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String accountId;
	private java.util.List<com.myspace.risk_analytics_orchestrator.Holdings> holdings;

	public Account() {
	}

	public java.lang.String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(java.lang.String accountId) {
		this.accountId = accountId;
	}

	public java.util.List<com.myspace.risk_analytics_orchestrator.Holdings> getHoldings() {
		return this.holdings;
	}

	public void setHoldings(
			java.util.List<com.myspace.risk_analytics_orchestrator.Holdings> holdings) {
		this.holdings = holdings;
	}

	public Account(
			java.lang.String accountId,
			java.util.List<com.myspace.risk_analytics_orchestrator.Holdings> holdings) {
		this.accountId = accountId;
		this.holdings = holdings;
	}

}