package com.myspace.risk_analytics_orchestrator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VarRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String correlationId;
	private java.lang.Boolean allAccounts;
	private Double confidence;
	private java.util.List<com.myspace.risk_analytics_orchestrator.Account> accounts;
	private String entityType;
	private String entityId;

	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public String getEntityId() {
		return entityId;
	}

	public void setEntityId(String entityId) {
		this.entityId = entityId;
	}

	public VarRequest() {
	}

	public java.lang.String getCorrelationId() {
		return this.correlationId;
	}

	public void setCorrelationId(java.lang.String correlationId) {
		this.correlationId = correlationId;
	}

	public java.lang.Boolean getAllAccounts() {
		return this.allAccounts;
	}

	public void setAllAccounts(java.lang.Boolean allAccounts) {
		this.allAccounts = allAccounts;
	}

	public java.util.List<com.myspace.risk_analytics_orchestrator.Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(
			java.util.List<com.myspace.risk_analytics_orchestrator.Account> accounts) {
		this.accounts = accounts;
	}

	public VarRequest(
			java.lang.String correlationId,
			java.lang.Boolean allAccounts,
			java.lang.String entityType,
			java.lang.Double confidence,
			java.util.List<com.myspace.risk_analytics_orchestrator.Account> accounts) {
		this.correlationId = correlationId;
		this.allAccounts = allAccounts;
		this.entityType = entityType;
		this.confidence = confidence;
		this.accounts = accounts;
	}

	@Override
	public String toString() {
		return "VarCalculationRequest [correlationId=" + correlationId
				+ ", allAccounts=" + allAccounts + ", entityType=" + entityType
				+ ", entityId=" + entityId + ", confidence=" + confidence
				+ ", accounts=" + accounts + "]";
	}

	public java.lang.Double getConfidence() {
		return this.confidence;
	}

	public void setConfidence(java.lang.Double confidence) {
		this.confidence = confidence;
	}

	public VarRequest(
			java.lang.String correlationId,
			java.lang.Boolean allAccounts,
			java.lang.Double confidence,
			java.util.List<com.myspace.risk_analytics_orchestrator.Account> accounts,
			java.lang.String entityType, java.lang.String entityId) {
		this.correlationId = correlationId;
		this.allAccounts = allAccounts;
		this.confidence = confidence;
		this.accounts = accounts;
		this.entityType = entityType;
		this.entityId = entityId;
	}

}